export const mille_miglia_images = [
  {
    id: 1,
    src: "stories/carrousel/first.webp",
    alt: "Mille Miglia",
    full: false,
    indexImage: 31,
  },
  {
    id: 2,
    src: "stories/carrousel/second.webp",
    alt: "Mille Miglia",
    full: true,
    indexImage: 32,
  },
  {
    id: 3,
    src: "stories/carrousel/third.webp",
    alt: "Mille Miglia",
    full: false,
    indexImage: 33,
  },
  {
    id: 4,
    src: "stories/carrousel/fourth.webp",
    alt: "Mille Miglia",
    full: true,
    indexImage: 34,
  },
  {
    id: 5,
    src: "stories/carrousel/fifth.webp",
    alt: "Mille Miglia",
    full: false,
    indexImage: 35,
  },
  {
    id: 6,
    src: "stories/carrousel/sixth.webp",
    alt: "Mille Miglia",
    full: false,
    indexImage: 36,
  },
  {
    id: 7,
    src: "stories/carrousel/seventh.webp",
    alt: "Mille Miglia",
    full: true,
    indexImage: 37,
  },
  {
    id: 8,
    src: "stories/carrousel/eighth.webp",
    alt: "Mille Miglia",
    full: false,
    indexImage: 38,
  },
];
