export const carrousel_images = [
  {
    index: 1,
    alt: "Becoming Ferrari",
    src: "/images_grid/grid_one.webp",
  },
  {
    index: 2,
    alt: "Making Ferrari",
    src: "/images_grid/grid_two.webp",
  },
  {
    index: 3,
    alt: "The Stories Of Ferrari",
    src: "/images_grid/grid_three.webp",
  },
  {
    index: 4,
    src: "/images_grid/grid_four.webp",
    alt: "Gallery",
  },
  { index: 5, src: "becoming/first_carrousel/first.webp", alt: "Adam" },
  { index: 6, src: "becoming/first_carrousel/second.webp", alt: "Adam" },
  { index: 7, src: "becoming/first_carrousel/third.webp", alt: "Adam" },
  { index: 8, src: "becoming/first_carrousel/fourth.webp", alt: "Adam" },
  { index: 9, src: "becoming/adam/first.webp", alt: "Adam" },
  { index: 10, src: "becoming/adam/second.webp", alt: "Adam" },
  { index: 11, src: "becoming/second_carrousel/first.webp", alt: "Penelope" },
  { index: 12, src: "becoming/second_carrousel/second.webp", alt: "Penelope" },
  { index: 13, src: "becoming/second_carrousel/third.webp", alt: "Penelope" },
  { index: 14, src: "becoming/second_carrousel/fourth.webp", alt: "Penelope" },
  { index: 15, src: "becoming/penelope/first.webp", alt: "Penelope" },
  { index: 16, src: "becoming/penelope/second.webp", alt: "Penelope" },
  { index: 17, src: "making/first_carrousel/first.webp", alt: "Chapter One" },
  { index: 18, src: "making/first_carrousel/second.webp", alt: "Chapter One" },
  { index: 19, src: "making/first_carrousel/third.webp", alt: "Chapter One" },
  { index: 20, src: "making/first_carrousel/fourth.webp", alt: "Chapter One" },
  { index: 21, src: "making/first_section/first.webp", alt: "Chapter One" },
  { index: 22, src: "making/second_section/first.webp", alt: "Chapter One" },
  { index: 23, src: "making/second_section/second.webp", alt: "Chapter One" },
  { index: 24, src: "making/second_section/third.webp", alt: "Chapter One" },
  { index: 25, src: "making/second_carrousel/first.webp", alt: "Chapter One" },
  { index: 26, src: "making/second_carrousel/second.webp", alt: "Chapter One" },
  { index: 27, src: "making/second_carrousel/third.webp", alt: "Chapter One" },
  { index: 28, src: "making/second_carrousel/fourth.webp", alt: "Chapter One" },
  {
    index: 29,
    src: "stories/section/first.webp",
    alt: "Mille Miglia",
  },
  {
    index: 30,
    src: "stories/section/second.webp",
    alt: "Mille Miglia",
  },
  {
    index: 31,
    src: "stories/carrousel/first.webp",
    alt: "Mille Miglia",
  },
  {
    index: 32,
    src: "stories/carrousel/second.webp",
    alt: "Mille Miglia",
  },
  {
    index: 33,
    src: "stories/carrousel/third.webp",
    alt: "Mille Miglia",
  },
  {
    index: 34,
    src: "stories/carrousel/fourth.webp",
    alt: "Mille Miglia",
  },
  {
    index: 35,
    src: "stories/carrousel/fifth.webp",
    alt: "Mille Miglia",
  },
  {
    index: 36,
    src: "stories/carrousel/sixth.webp",
    alt: "Mille Miglia",
  },
  {
    index: 37,
    src: "stories/carrousel/seventh.webp",
    alt: "Mille Miglia",
  },
  {
    index: 38,
    src: "stories/carrousel/eighth.webp",
    alt: "Mille Miglia",
  },
];
