export const carrousel_images = [
  {
    title: "Becoming",
    description: "Becoming Ferrari",
    src: "/images_grid/grid_one.webp",
    chapter: "Chapter One",
    href: "/becoming",
  },
  {
    title: "Making",
    description: "Making Ferrari",
    src: "/images_grid/grid_two.webp",
    chapter: "Chapter Two",
    href: "/making",
  },
  {
    title: "The Stories Of",
    description: "The Stories Of Ferrari",
    src: "/images_grid/grid_three.webp",
    chapter: "Chapter Three",
    href: "/stories",
  },
  {
    title: "Gallery",
    description: "Gallery",
    src: "/images_grid/grid_four.webp",
    chapter: "View",
    href: "/becoming",
  },
  { id: 1, src: "becoming/first_carrousel/first.webp", alt: "Adam" },
  { id: 2, src: "becoming/first_carrousel/second.webp", alt: "Adam" },
  { id: 3, src: "becoming/first_carrousel/third.webp", alt: "Adam" },
  { id: 4, src: "becoming/first_carrousel/fourth.webp", alt: "Adam" },
  { id: 1, src: "becoming/second_carrousel/first.webp", alt: "Penelope" },
  { id: 2, src: "becoming/second_carrousel/second.webp", alt: "Penelope" },
  { id: 3, src: "becoming/second_carrousel/third.webp", alt: "Penelope" },
  { id: 4, src: "becoming/second_carrousel/fourth.webp", alt: "Penelope" },
  { id: 1, src: "making/first_carrousel/first.webp", alt: "Chapter One" },
  { id: 2, src: "making/first_carrousel/second.webp", alt: "Chapter One" },
  { id: 3, src: "making/first_carrousel/third.webp", alt: "Chapter One" },
  { id: 4, src: "making/first_carrousel/fourth.webp", alt: "Chapter One" },
  { id: 1, src: "making/second_carrousel/first.webp", alt: "Chapter One" },
  { id: 2, src: "making/second_carrousel/second.webp", alt: "Chapter One" },
  { id: 3, src: "making/second_carrousel/third.webp", alt: "Chapter One" },
  { id: 4, src: "making/second_carrousel/fourth.webp", alt: "Chapter One" },
  {
    id: 1,
    src: "stories/carrousel/first.webp",
    alt: "Mille Miglia",
    full: false,
  },
  {
    id: 2,
    src: "stories/carrousel/second.webp",
    alt: "Mille Miglia",
    full: true,
  },
  {
    id: 3,
    src: "stories/carrousel/third.webp",
    alt: "Mille Miglia",
    full: false,
  },
  {
    id: 4,
    src: "stories/carrousel/fourth.webp",
    alt: "Mille Miglia",
    full: true,
  },
  {
    id: 5,
    src: "stories/carrousel/fifth.webp",
    alt: "Mille Miglia",
    full: false,
  },
  {
    id: 6,
    src: "stories/carrousel/sixth.webp",
    alt: "Mille Miglia",
    full: false,
  },
  {
    id: 7,
    src: "stories/carrousel/seventh.webp",
    alt: "Mille Miglia",
    full: true,
  },
  {
    id: 8,
    src: "stories/carrousel/eighth.webp",
    alt: "Mille Miglia",
    full: false,
  },
];
